### ISSUE TITLE
Doesn't work in Marshmallow 

### ISSUE THREAD

**Issue by terrorist96** [qwerty12/PlayStoreLinkInAppInfo#3]
Worked for me in Kitkat. Doesn't work in Marshmallow.

**Comment by Download7** [comment]
It's not working for me in lollipop 5.1.1

**Comment by Djfe** [comment]
Same for me, pls think about updating your useful app @qwerty12 :)

**Comment by ryankhart** [comment]
Same for me as well. This is the main reason why I use xposed framework on Android. Please consider updating it for Marshmallow.

**Comment by Download7** [comment]
I actually want this mod so much I signed up to github just to ask for assistance

**Comment by qwerty12** [comment]
I apologise, but I won't be doing so for a number of reasons:
- I don't have the Android SDK installed anymore. (And given the state of my system currently, I'm sure I'd run into problems while trying to set it up.)
- I'm not a good Android developer in the slightest.
- My M8 won't be getting any updates past Marshmallow (and I'm still in love with the phone, so I really don't feel the need to buy a new one), so I wouldn't be able to maintain this for future updates even if I wanted to.
- I, erm, was going to include "the Xposed module XBridge is far superior to this one", but I see that that's not been updated for Marshmallow, either...

**Comment by Djfe** [comment]
Thx for answering though :)
Maybe someone find's interest and forks your project to update it.
